### ISSUE TITLE
Sync contacts & agenda

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-mobile#1]

**Comment by benoitb85** [comment]
Is it by writing a comment here that we vote in favor of that feature request ? If yes, I just did :) Would help me leave Google.

**Comment by jsilvestre** [comment]
Hello @benoitb85, you can already sync your contacts and calendars, following: http://cozy.io/fr/mobile/calendar.html
Let us know on the forum, IRC or https://github.com/cozy/cozy-sync/issues if you have any trouble, we'll be glad to help.

But it is noted you "+1'ed" the feature!

**Comment by benoitb85** [comment]
Thank you very much, this is great information.

**Comment by mickours** [comment]
If contact synchronisation is not done by the application but by an external CardDav/CalDav client, why is there a ``contact synchronisation`` check box on the configuration of the app?
This lead to misunderstanding what the application do.
So please remove this configuration entry or explain clearly what is it purpose.

**Comment by aenario** [comment]
@mickours, 

Some users complained that they needed to install yet another app to sync contacts with cozy (a CardDav). Moreover, this is not easy to explain to people who are not technical enough to know CardDav. So we decided to add the contact sync to the cozy app itself (not using CardDAV but a custom protocol).

However, this feature is still experimental, so we keep the documentation about currently working CardDAV sync. Once this feature (and its sibling, calendar synchronization) is stable, we will explicit the documentation about CardDAV/CalDAV to say "If you use the cozy application on android, no need to read this".

**Comment by poupotte** [comment]
We can now synchronize contacts and calendars with mobile application.
