### ISSUE TITLE
Cozy app make the whole phone unstable

### ISSUE THREAD

**Issue by FromBabylon** [cozy/cozy-mobile#210]
Hi,

Non long ago I had lot of troubles with my phone, regularly lagging a lot making it unusable for a few minutes. I told myself this was a system problem and decided a complete reinstall with a ROM switching. On the clean install everything was working smoothly again. As soon as I install cozy app again the same problems came back. Phone not responding, especially when uploading camera pictures.

I do not know exactly how to help investigate on that, wether or not I'm alone in this case. 

Here is my actual phone : 

![screenshot_20160314-151124](https://cloud.githubusercontent.com/assets/9169020/13747160/36bd4abc-e9f7-11e5-9078-2ac3d7957fb1.png)

**Comment by poupotte** [comment]
Hi @FromBabylon ,

thanks for your feedback.

Can you send us your logs ? (See ''Send debug information" in our [documentation](https://docs.cozy.io/en/mobile/trouble.html) )

Zoé

**Comment by FromBabylon** [comment]
Looks like I can't do it (my email app won't add the logs if I click on "Send logs" in cozy). Where can I get the file on the phone and send it manually ?

**Comment by frankrousseau** [comment]
That's a big issue. Thank you @FromBabylon for reporting.

**Comment by kosssi** [comment]
Hello @FromBabylon,

Thanks for your contribution.

We don't have logs file. It's in localStorage.
To understand a little more, I have questions:
- What is your CozyMobile version ?
- Have you tested to remove "Backup images" in configuration ?
- It's the same if you are with or without wifi ?

Thanks,

**Comment by FromBabylon** [comment]
Hi,

I could send the log using a gmail adress. 

 - Cozy Mobile v1.0.0
 - Haven't tested anything since I've just realized the problem was linked to cozy app
 - I think it only happens with WIFI. I'll try to reproduce it

Is there any android log that could help ?

Thanks

**Comment by kosssi** [comment]
Hello @FromBabylon ,

Thank you for sending your logs. There are all inside ;)
Have you always the problem?

Simon

**Comment by kosssi** [comment]
Hello @FromBabylon 
Have you always the problem with the new version of Cozy Mobile v1.1.2?

**Comment by FromBabylon** [comment]
HI, 

sorry for coming so late, I was really busy this days. 

So the problem didn't appear again but I didn't have any long pictures sync to launch. Did you find something in the logs ? 

I thought as it may not be cozy itself but a simple wifi + low battery that makes the phone lag. Which means that would have been a coincidence.

**Comment by kosssi** [comment]
Hello @FromBabylon 

Can you close this issue if you don't have new lag?

Thanks

**Comment by kosssi** [comment]
I close it, @FromBabylon if you have any problem create new issue.

Thanks a lot,

**Comment by FromBabylon** [comment]
Sorry I didn't close. Re-synced my whole phone pictures in Wi-Fi without any troubles ;-) 

I think it was not due to cozy but a 'quite-low' battery state and high Wi-Fi usage. I did have it again with cozy disabled. Sorry for false worries !
