### ISSUE TITLE
Wrong translation for "Incorrect password" message

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-mobile#23]
The message "Incorrect password" is still displayed in English while my app is in French.

**Comment by jacquarg** [comment]
The error message comes directly from the cozy, and is already translated.
With mine, the message is "Mot de passe incorrect." 
It's probably a proxy thing, but changing language in "Configure cozy" has no effect on it, as on the cozy's login page.

Could we assume that user's have the login page of their cozy in the language they expect ?

**Comment by clochix** [comment]
@frankrousseau up

**Comment by frankrousseau** [comment]
Ok
