### ISSUE TITLE
Endless backup loop for Cozy pictures

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-mobile#25]
@FromBabylon reported on the forum

> I can see the files I have in CozyFiles but it appears that "Synchronize phone pictures" doesn't work. Mobile app goes into endless backup loop (logo turn without ending)

**Comment by FromBabylon** [comment]
There is some news. After purchasing a domain name and configuring cozy to use it, pictures start to sync but stop after 6 ones. And then go the loop

**Comment by frankrousseau** [comment]
We will publish soon a new version. We'll keep you informed. Once you get it. The best will be to resync your app from scratch.

**Comment by FromBabylon** [comment]
Can't wait ;-) 
I use Cyanogenmod 11 maybe this has something to do ? It's strange as the first 6 pictures are in the files app, well tagged.

**Comment by FromBabylon** [comment]
Same problem after update. Can't upload more than 6 pictures. And it's always the same 6 first that get sync.

**Comment by frankrousseau** [comment]
Ok, sorry that the problem is still there. We'll inspect it next week.

**Comment by FromBabylon** [comment]
No problem. Which logs should I invest in ? That might be a stupid question as I can get some pictures sync but, is there something more to open in firewall ? 
I'm gonna try to delete those pictures on my phone and see if something get sync.

**Comment by frankrousseau** [comment]
We made many fixes. Could you try again ?

**Comment by FromBabylon** [comment]
I tried again on a fresh cozy install (LXC container).

Things seem to be working better but still problems. Here is what happened :
 1. Installing Cozy Mobile app (dirty unicorn ROM)
 2. Launching it, sync begin for 210 pictures. 
 3. After 52 pictures sync stopped. 
 4. Relaunch cozy mobile
 5. Sync started for 158 pictures
 6. No more pictures uploaded but sync "finished".
 7. Start from 5 again automatically

Reset cozy mobile to zero and try again same problem.
