### ISSUE TITLE
Android app hangs on contacts sync

### ISSUE THREAD

**Issue by eklem** [cozy/cozy-mobile#252]
Hi, I've downloaded the Adroid app and set it to synchronize everything possible. When it starts synchronizing, it hangs on `Step 4/6: Contacts synchronization.` 

It shouldn't do that, should it? I'm using the version from Google Play.

![screenshot_20160517-135741](https://cloud.githubusercontent.com/assets/236656/15356445/0141900c-1cf9-11e6-99b5-b02184881153.png)

**Comment by clochix** [comment]
Hi @eklem,

Which version of the application are you using? We published yesterday version 1.2.8 that should fix this issue.

**Comment by eklem** [comment]
I was using an older version (installed a couple of days ago), but upgraded to 1.2.8. Still got the issue. And I've enabled calendar sync for Cozy from the contacts app.
Now, though, it sends/receives data for a bit longer time.

**Comment by kosssi** [comment]
hello @eklem ,

Can you test with the last release? : https://github.com/cozy/cozy-mobile/releases/tag/v1.2.9
Your Cozy address is on *.cozycloud.cc ?

**Comment by eklem** [comment]
Sorry for late answer. Yes, it's on *.cozycloud.cc. Working now, thanks!
