### ISSUE TITLE
Do not verify certificate

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-mobile#27]
Like for the desktop client, we probably can remove the verify certificate option from PouchDB synchronization: https://github.com/cozy-labs/cozy-desktop/pull/82

**Comment by poupotte** [comment]
Remove certificate is insecure and user can follow this [tuto](https://davdroid.bitfire.at/faq/entry/importing-a-certificate/) if his cozy has an self-signed certificate.
