### ISSUE TITLE
Weird UX when opening a file

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-mobile#274]
Steps to reproduce
===

- on the android app, download a large file (e.g. music track or video).
- then click on the file to open it

Expected
===

I expect opening the file to be instantaneous, as I've downloaded it on the local device.

Observed
===

There's a small loading bar that shows up when clicking on the file, suggesting it is getting downloaded again, or something else. Thinking about it, I guess this is because the file is getting extracted from the pouchdb (within the app) to the real filesystem (in a temporary location, probably). Although I understand the technical constraint here (in particular, the file is duplicated => more SD memory taken, metadata is duplicated and needs sync, etc.), it seems quite weird to not be able to Just Open the file and have it available from other apps. For instance, I'd expect a mp3 file that I've downloaded to be available in the Android music player, by default.

**Comment by kosssi** [comment]
Hello @bnjbvr 

This bug was fixed. When the app display progress bar it's only to download the file. The binary are not on pouchdb on mobile ;) So we don't have duplicate binary.

@babolivier create this issue https://github.com/cozy/cozy-mobile/issues/303 to display all file on default app. Can you close this issue?

Thanks for your contribution,

**Comment by bnjbvr** [comment]
Yes, please go ahead with closing.


On Thu, Aug 11, 2016, at 12:46, Simon wrote:
> Hello @bnjbvr[1]
> This bug was fixed. When the app display progress bar it's only to
> download the file. The binary are not on pouchdb on mobile ;) So we
> don't have duplicate binary.
> @babolivier[2] create this issue #303[3] to display all file on
> default app. Can you close this issue?
> Thanks for your contribution,
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[4], or mute the thread[5].
>

Links:

  1. https://github.com/bnjbvr
  2. https://github.com/babolivier
  3. https://github.com/cozy/cozy-mobile/issues/303
  4. https://github.com/cozy/cozy-mobile/issues/274#issuecomment-239128147
