### ISSUE TITLE
No menu displayed

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-mobile#277]
[Reported in the forum](https://forum.cozy.io/t/mon-appli-mobile-cozy-na-pas-de-menu/2905/2): 

> J'ai pas mal galéré à installer l'appli mobile sur mon smartphone Android 4.3, l'installation bloquant systématiquement sur la synchronisation des photos. J'ai finalement réussi à installer l'appli en désactivant cette fonction. La fonction "Fichiers" fonctionne, la synchronisation des contacts et du calendrier aussi, mais l'appli n'a pas de menu !

**Comment by kosssi** [comment]
This issue is for Android 4.3 but now it's only on compatible with 4.4 ;)
