### ISSUE TITLE
Menu Image croped

### ISSUE THREAD

**Issue by Schoumi** [cozy/cozy-mobile#278]
The image displayed in the menu next to each entry (Files, Syncrhonize and Configuration) are croped on my phone (LG G3S). 
The image is croped also in about section in the Configuration Screen.

**Comment by clochix** [comment]
Thanks for reporting @Schoumi 
Is it possible to add a screenshot?

**Comment by Schoumi** [comment]
![screen](https://cloud.githubusercontent.com/assets/8394962/16989771/be790c5e-4e95-11e6-82a3-e7b25356df0c.png)

**Comment by kosssi** [comment]
thanks @Schoumi

**Comment by kosssi** [comment]
@Schoumi have you same issue with new app (v2.0.0) ?

**Comment by Schoumi** [comment]
Solved

**Comment by kosssi** [comment]
💌
