### ISSUE TITLE
Display of Folder list incomplete

### ISSUE THREAD

**Issue by Schoumi** [cozy/cozy-mobile#306]
In a folder i have 60 folders and the Mobile app, display only 40 of them, not all. When it sync for the first time just after the install it show the right number of file and Folder. 
So the problem is a display problem to me.

**Comment by kosssi** [comment]
@Schoumi @encolpe with [new release v2.0.0](https://github.com/cozy/cozy-mobile/releases/tag/v2.0.0) have you this problem ?

**Comment by Schoumi** [comment]
seems to be good. All my folder are now listed.

**Comment by kosssi** [comment]
@Schoumi can you close this issue ? 💃

**Comment by kosssi** [comment]
👍
