### ISSUE TITLE
Can't log in to my account

### ISSUE THREAD

**Issue by sd65** [cozy/cozy-mobile#44]
Hi all,

I've just tested this app but I stuck at the first screen of the app "Configuration 1/3". 
I entered my cosy address (cloud.XXX.fr) and my password but it's not working. I even tried without any reverse proxy by connecting directly to my cosy docker by serverIp:6500 but it's not working ('Echec de la connexion").

The strange thing is I can connect to my cozy with my mobile browser (with both adresses).

What can I provide you to debug this ? :)

**Comment by aenario** [comment]
The mobile app will always connect through https. 
Does your docker setup include an nginx with certificates ?
If it is self-signed, you will need to import in on android, using for instance CADroid

**Comment by sd65** [comment]
Yeah it works !
Thank you, I didn't imagine this would be a problem. I re-created my certificates using CA=True [using this](http://www.leftbrainthings.com/2013/10/13/creating-and-importing-self-signed-certificate-to-android-device/) and then I imported them with CADroid.

This is logical and good, but the procedure is bit heavy. Wouldn't it be possible to have a checkbox at this screen to bypass the check of the certificate ?

**Comment by aenario** [comment]
Well, we believe the age of self signed certificate is coming to an end with @letsencrypt and we want to keep this screen as trivial as possible (entering an URL instead of a login/email is already not obvious for non technical users), so we wont be adding a checkbox. 

However #43 will mention self-signed certificate as a possible cause for error.

**Comment by sd65** [comment]
Thanks for pointing out to me @letsencrypt, can't wait to use it ;)

**Comment by frankrousseau** [comment]
We have a lot of self hosted users. That option would be nice.
