### ISSUE TITLE
password with ":" is not supported on stage 2 (device naming)

### ISSUE THREAD

**Issue by dhardy92** [cozy/cozy-mobile#53]
My password use to have column ":" in it. It seams this character ( at least) is OK on first screen, but app complains on device name form (second screen) for bad password.

**Comment by poupotte** [comment]
Thanks @dhardy92 for your report, I'll have a look ASAP.

**Comment by poupotte** [comment]
Problems seems come from extractCredentials from proxy : https://github.com/cozy/cozy-proxy/blob/master/server/controllers/devices.coffee#L13 . I'll correct it.

**Comment by frankrousseau** [comment]
@poupotte What is the stage of this issue? Users keep on facing the problem and the error message is ugly (unexpected token). It's harmful for the user experience.

**Comment by poupotte** [comment]
This problem was fixed (changes on proxy and mobile).

**Comment by frankrousseau** [comment]
In fact, it's related to another problem (the user can go to step 2 with wrong credentials).
