### ISSUE TITLE
The application consume to much data on 3G, even with synchronization enable only on WiFi

### ISSUE THREAD

**Issue by vdubus** [cozy/cozy-mobile#57]
I had a big problem yesterday : the application consumed way to much of my 3G Data (+200Mo on background). But, when looking at the configuration, it was set to only synchronized when WiFi was enable (maybe my WiFi was enable, but it wasn't connect to anything)...

I had to uninstall it to avoid this problem... As I was outside my country, it cost me a lot of money : 40€.

**Comment by babolivier** [comment]
Hi @vdubus,
This is a known bug, still being worked on. Until this is fixed, I advise you to manually restrict background data on mobile networks (with Lollipop, go to your data usage settings, then select the Cozy app in the list, and check the "Restrict app background data" option).

**Comment by vdubus** [comment]
Can you link me the ticket for this know bug ?

**Comment by babolivier** [comment]
By "known bug", I meant that Cozy Cloud's team is aware of it, and is currently trying to fix it. I don't think any ticket has been opened about it yet.

**Comment by frankrousseau** [comment]
Yes thank @vdubus for reporting!

**Comment by jacquarg** [comment]
More reports of this bug here: https://forum.cozy.io/t/consommation-donnees-cozy-android-mad/1223/1
But still need more precises data (logs) to go further and solve this :/

**Comment by ZeHiro** [comment]
It seems the moficiation of "non wifi/wifi" parameter is not taken into account until restart of mobile application (kill and restart).

**Comment by wotanii** [comment]
has there been any progress on this?

**Comment by kosssi** [comment]
We work on this, I think before 21 January it's fix.

**Comment by poupotte** [comment]
We have still some works to solve this issue which demands a big refactoring but @kosssi and @jacquarg continue to work on it :)

**Comment by poupotte** [comment]
This issue should be solved now. I close it. If someone has still this issue, don't hesistate to reopen it.
