### ISSUE TITLE
Home icon is not fully colored when tapped

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-mobile#60]
Hi,

when I tap on the "home" icon button, the icon becomes orange (instead of blue). However, only a part of the icon/button is filled.

I took a screenshot while pressing the button :

![screenshot_2015-07-28-23-37-03](https://cloud.githubusercontent.com/assets/3419050/8951466/56cd77ec-35ce-11e5-985b-ad7edf23995d.png)

When navigating to a subdirectory only the rectangle shape (same size as here) is filled too, not the arrow : 

![screenshot_2015-07-29-08-49-44](https://cloud.githubusercontent.com/assets/3419050/8951529/efce5254-35ce-11e5-958b-185c5d25f6fa.png)

I know it is not important but it kinda looks messy.

My mobile is a Nexus 4 (Android 5.1.1)

**Comment by clochix** [comment]
Thanks for reporting @nicofrand, we'll have a look ☺
