### ISSUE TITLE
Alert "Not Found" when resync from beginning

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-mobile#61]
When clicking on "Sync" in the "Configuration" menu, an alert appears reading "Not found";
This likely comes from a configuration issue from my side but I feel like the error should be more clear.

I only have a directory (without any file) to sync. I unchecked the contacts and pictures synchronization.

![screenshot_2015-07-29-08-52-28](https://cloud.githubusercontent.com/assets/3419050/8955725/9ee19920-35ef-11e5-8b84-24c2aeb544ea.png)

**Comment by jacquarg** [comment]
Must be the same problem as reported here : https://forum.cozy.io/t/cozymobile-erreur-a-linitialisation/1087 .
App complain about route to db views not found, but required apps are installed in the cozy, and the mobile app work well then.

**Comment by jacquarg** [comment]
Some more log from, 
I still do not understand the issue but these informations definitely helps, thanks @nicofrand ! 

```
 check+credentials+done
 starting+first+replication
 initialReplication
 copyView+1438774315318
 [object+XMLHttpRequest]
 end+of+inital+replication+1438774315381
```
![screenshot_2015-08-05-15-03-36](https://cloud.githubusercontent.com/assets/1233038/9087789/1d85cc36-3b8d-11e5-9807-26db683a239b.png)


Which means that route `/_design/file/_view/files-all/` returns 401 .

**Comment by nicofrand** [comment]
Dans les logs du proxy j'ai bien
`[Wed, 05 Aug 2015 15:30:59 GMT] - GET /cozy/_design/file/_view/files-all/ - 401 - 8.935 ms -  67` en effet.

Mais pourquoi ? J'ai bien pu ajouter mon device, mes identifiants sont bons…

**Comment by nicofrand** [comment]
Pour la seconde erreur, j'ai entre temps réinstallé mon instance de cozy et files ne fonctionne pas (erreur 500). Ça explique sûrement l'erreur 401 sur GET /cozy/_design/file/_view/files-all/ ?
Il y a également eu la mise à jour de cozy-mobile pour Android.

Pardon, je n'avais pas pensé à vérifier que files tournait bien cette fois-ci.
D'ailleurs, si l'utilisateur désinstalle l'application files de son cozy, que se passe-t'il sur la version mobile ? Un "Unauthorized" ? (En quel cas il serait bon de prévenir l'utilisateur qu'il doit installer l'application files, voire la lancer si elle est stoppée et ne se lance pas toute seule lors d'une requête GET /cozy/_design/file/_view/files-all/.)

**Comment by nicofrand** [comment]
J'ai depuis réinstallé cozy et files mais j'ai toujours cette erreur 401.

**Comment by jacquarg** [comment]
Merci pour le log ! J'espère pouvoir comprendre cette fois !!

**Comment by poupotte** [comment]
Bonjour @nicofrand ,

dans votre interface `Status` avez-vous des devices d'enregistrés ?
En effet, au moment de l'enregistrement du téléphone auprès de votre Cozy, ce dernier crée un device permettant au téléphone de s'identifier par la suite. Si ce device a été supprimé (suite à une mauvaise manipulation ou une réinstallation), cela pourrait expliquer que le téléphone n'a plus accès au Cozy et ne peux donc plus synchroniser les fichiers.

Si l'utilisateur désinstalle son application Files, cela ne pose pas de problème. Il suffit, pour le moment, d'installer une première fois Files pour générer les vues qu'utilise le mobile. Ce problème devrait se régler rapidement en permettant au mobile de créer directement ses propres vues.

Zoé

**Comment by nicofrand** [comment]
Le device était bien listé oui.

J'ai depuis réinstallé l'application puis réinstallé et il y a eu des mises
à jour de files, je n'arrive plus à reproduire le bug.
