### ISSUE TITLE
Error finding photo to upload

### ISSUE THREAD

**Issue by jacquarg** [cozy/cozy-mobile#64]
Error while converting Android file URI to File object :

Error+in+Error+callbackId:+File813823000+:+TypeError:+Cannot+read+property+'name'+of+undefined
processMessage+failed:+Error:+TypeError:+Cannot+read+property+'name'+of+undefined
processMessage+failed:+Stack:+TypeError:+Cannot+read+property+'name'+of+undefined
++++at+file:///android_asset/www/javascripts/app.js:3004:40
++++at+file:///android_asset/www/javascripts/app.js:2027:14
++++at+onError+(file:///android_asset/www/javascripts/app.js:1998:12)
++++at+fail+(file:///android_asset/www/plugins/org.apache.cordova.file/www/resolveLocalFileSystemURI.js:39:26)
++++at+Object.cordova.callbackFromNative+(file:///android_asset/www/cordova.js:288:52)
++++at+processMessage+(file:///android_asset/www/cordova.js:1070:21)
++++at+Function.androidExec.processMessages+(file:///android_asset/www/cordova.js:1107:13)
++++at+pollOnce+(file:///android_asset/www/cordova.js:963:17)
++++at+pollOnceFromOnlineEvent+(file:///android_asset/www/cordova.js:953:5)
processMessage+failed:+Message:+F09+File813823000+n1

Future PR will catch error before accessing 'name' attribute, but the underlying problem isn't known.

**Comment by poupotte** [comment]
@jacquarg , any news about this issue ?

**Comment by jacquarg** [comment]
No. And as the app now hide the problem (catching the error), we can't know if it's rare or not.

**Comment by kosssi** [comment]
This bug does not exist now.
