### ISSUE TITLE
Application keeps to crash with no reason

### ISSUE THREAD

**Issue by jacquarg** [cozy/cozy-mobile#65]
Application keeps to crash with no reason (could be when mobile network is back on).

**Comment by ZeHiro** [comment]
I would precise mobile data back on.

**Comment by jacquarg** [comment]
@ZeHiro : do you still encounter this issue on latests versions ?

**Comment by ZeHiro** [comment]
@jacquarg 
I changed of device, and I have no problem anymore. I cannot say it is related. I close.

**Comment by jacquarg** [comment]
Thanks !
