### ISSUE TITLE
Sync not working with Android 5.1.1

### ISSUE THREAD

**Issue by l0415** [cozy/cozy-mobile#66]
The sync feature is not working on my OnePlus One running Android 5.1.1
There's an infinite circle on the top right of the file list but nothing append, No blue message saying "syncing photos" or anything

EDIT :The sync feature is not working with contacts too, I've used DAVdroid to make it works

**Comment by clochix** [comment]
Thanks for reporting @l0415 ☺

@jacquarg could you have a look at this one ?

**Comment by clochix** [comment]
See also [this thread](https://forum.cozy.io/t/chargement-infini-pour-la-synchronisation-de-lapplication-cozy/823). Maybe a problem with Android 5.1.1 ?

**Comment by jacquarg** [comment]
Hello @l0415 ,
I don't precisely figure out the problem, by I try something in last 0.1.10 version. Could you try it. And if it still doesn't work, could you please send a repport with log (with dedicated button in config screen of the app).

Thanks a lot

**Comment by jacquarg** [comment]
Reported as solved here : https://forum.cozy.io/t/chargement-infini-pour-la-synchronisation-de-lapplication-cozy/823/7?u=jacquarg

Fixed with v0.1.10 . To close.

**Comment by clochix** [comment]
Thanks a lot @l0415 for reporting and @jacquarg for fixing ☺
