### ISSUE TITLE
"Wifi only" sync restriction only taken into account when app is restarted

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-mobile#69]
It appeared to me that the modification of "only sync on wifi" restriction is only taken into account when the application is restarted. 

To reproduce : 
1. open application
2. modify setting (allow/disallow sync on 3G)
3. try to sync : the behaviour is unchanged i.e : not conform to selected setting
4. Restart application
5. Try to sync : the behaviour is conform to the setting

Configuration : self hosted
Android : 4.2.2
cozy-mobile : 0.1.10

**Comment by clochix** [comment]
Thanks for reporting @ZeHiro ☺
@jacquarg did you see this one ?

**Comment by jacquarg** [comment]
Yes I saw it, and did some investigations about it. I should have share. I reproduce it once ( UI tap event not fired on checkboxes ! ), but  I am waiting for the UI update to work on it.
