### ISSUE TITLE
Note field not always updated

### ISSUE THREAD

**Issue by jacquarg** [cozy/cozy-mobile#71]
Scenario:
- create a contact on phone.
- sync with cozy
- add a note in cozy's interface
- sync
- no note in phone.

**Comment by jacquarg** [comment]
Fixed for 0.1.11 (here : https://github.com/jacquarg/cordova-plugin-contacts/commit/023de712a98722399152ddeb2763264a60139e2d )

**Comment by poupotte** [comment]
It works well, thanks @jacquarg
