### ISSUE TITLE
Experiment with using Crosswalk to support older Android devices

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-mobile#78]
I am just leaving this here as a reminder of the project.

The cozy-mobile application is crashing a lot with android 4.0 & 4.2, due to instabilities in the native WebView renderer.

It appears there is a replacement WebView called Crosswalk which solves these problems.
https://crosswalk-project.org/documentation/cordova/cordova_4.html

If users starts to ask for support of older android, it might prove to be the solution.

**Comment by kosssi** [comment]
Now app compatibility is 4.4, so I close this issue
