### ISSUE TITLE
Sync continues after losing Wifi

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-mobile#81]
Reported by a user : 
 - he checked the option to only sync when connected to Wifi;
 - started to sync its photos while connected to its home Wifi;
 - leave home, switching from Wifi to GSM;
 - the sync didn't stop.

App version: 0.1.10

**Comment by jacquarg** [comment]
I fix this in june, but I also just fix a typo and adopt a paranoiac approach on this subject in current PR. Problem should be solved with upcoming version.

**Comment by poupotte** [comment]
Thanks @jacquarg :+1:
