### ISSUE TITLE
Cannot open file with "#" in its name

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-mobile#89]
**Steps to reproduce:**

0. On a desktop browser, go to *Files* and rename one of your file into "File #1"
0. Sync your mobile cozy
0. Try to open the file you just renamed

**Whats happens:**

An error message is prompted: "Alert: undefined"

**Comment by clochix** [comment]
Thanks for reporting @nicofrand 
@jacquarg any idea ?

**Comment by jacquarg** [comment]
We have a problem with filenames with ':' in their name (https://github.com/cozy/cozy-mobile/blob/master/www-src/app/replicator/replicator_backups.coffee#L140) , '#' may cause similar issue.
I will have a deeper look !
